spring.application.name=campusly

# Server
server.port=8081

# Datasource (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/campusly
spring.datasource.username=root
spring.datasource.password=kratoz_8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Connection pool (HikariCP defaults are fine; override if needed)
spring.datasource.hikari.maximum-pool-size=10

# Static file upload folder (absolute or relative)
campusly.uploads.path=uploads

# JWT (simple config)
jwt.secret=c5f8f781589b02af8731de31f2e0312f6c62ca0b418a8e29f2deb7cfe4006176
jwt.expiration-ms=3600000

# Logging
logging.level.org.springframework=INFO
logging.level.com.campusly=DEBUG

razorpay.key.id=
razorpay.key.secret=
razorpay.currency=
