spring.application.name=campusly

# Server
server.port=3031

# Datasource (MySQL)
spring.datasource.url=jdbc:mysql://
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection pool
spring.datasource.hikari.maximum-pool-size=10

# Static file upload folder
campusly.uploads.path=uploads

# JWT
jwt.secret=c5f8f781589b02af8731de31f2e0312f6c62ca0b418a8e29f2deb7cfe4006176
jwt.expiration-ms=3600000

# Logging
logging.level.org.springframework=INFO
logging.level.com.project.lms=DEBUG

spring.web.resources.static-locations=classpath:/frontend/
